language: node_js
node_js:
- '4.0'
deploy:
  provider: npm
  email: simon.menke@gmail.com
  api_key:
    secure: Mn+Y+N2c76hmf70w3qX9aspdMtyxKq72fHpkzzl6xRcrF7r4yJy9p/tCcmtVjWFHRelq5xZfZM8pzyeUP9IPZy6mUe454s0n9+SgOs2jbKzbsckoWiB7bOaIq7rgtNtUxNxolqDOmTC6zIhWiD4j5BMaSMMdoLPnjiq9Ez4Dyn3l569EsjGaILqf/7y1C5LRmqqHZR1IlH+hyLw8ia7TkaStPXbGrUgKCWd79+3VBkha6KQ2GFffM7pqLld5rXTwlRjj0221GOEGYVspew6S5RXN14h0TNbJfRoWay6YidOaFUSzoNCshgYha3QIigqXXTJHz69fgFg8K24q4KMPlkWz0aWCMS3Np8zlQWwLKIRKSlIsvRjmqIti1jtOnYcwwoyjNSwAnN8wqkxx+60gkVm92AtHNS6rcVffn+L3vBStBeyqszu7mxXKV4oGPLCNemGfe+STRth/SxaHgWonpWPBviEHyla0uO64f4G5JkjsEuVS8bbeC2ip2NleWtypkexJAiH9dTEhmemjAgLoBOK1rhS3gYOnK8lYlSl8ApU+O1O+ygow3GcGN9EVuUtTFww6UQ8iQUW2k+JEg7KsJjssbPyV7dthDid+WHxoHGpKM3xDuuhw+kboVOZUnvEmecZlqmtBn/kIxCpQtfPglGItgrIktTZuiPhBK7loIUI=
  on:
    tags: true
    repo: mrhenry/ng-haraway
